global:
  smtp_smarthost: smtp.exmail.qq.com:465
  smtp_from: zhuzhikai@leinao.ai
  smtp_auth_username: zhuzhikai@leinao.ai
  smtp_auth_password: Whyz657093
templates:
- "/etc/alertmanager/template/*.tmpl"
route:
  receiver: pai-alert
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  group_by: [alertname]
receivers:
  - name: "pai-alert"
    email_configs:
      - to: 2469209157@qq.com
        require_tls: false
        #html: '{{template "email.pai.html" . }}'
        headers:
          subject: '{Subject:"Warning Email!!!!"}'

